# Generated by Django 4.1.5 on 2023-01-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddParkingSlots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('total_slots', models.IntegerField(null=True)),
                ('available_slots', models.IntegerField(null=True)),
                ('booked_slots', models.IntegerField(default=0, null=True)),
                ('parking_session', models.CharField(max_length=100)),
                ('booking_start_time', models.CharField(max_length=100)),
                ('booking_end_time', models.CharField(max_length=100)),
                ('pin_number', models.CharField(max_length=10)),
                ('parking_charge', models.IntegerField(default=50, null=True)),
                ('qr_code', models.ImageField(null=True, upload_to='qr_images')),
            ],
            options={
                'db_table': 'parking_slots',
            },
        ),
    ]
