# Generated by Django 4.1.5 on 2023-01-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=300)),
                ('license_number', models.CharField(max_length=300)),
                ('profile', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='BookingSlots',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_date', models.DateField(max_length=100)),
                ('in_time', models.DateTimeField(null=True)),
                ('out_time', models.DateTimeField(null=True)),
                ('total_parking_time', models.CharField(max_length=1000, null=True)),
                ('total_charges', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='checkIn', max_length=100, null=True)),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.addparkingslots')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'booking_slots',
            },
        ),
    ]
